.github/workflows/publish-eslint-config.yml
The previous version of this workflow had an error due to my misunderstanding of Github workflow syntax (it would publish on every push to `main`, not only on tag pushes to `main` as I intended) and I didn't test it well enough to catch this. (The good news is that the job itself worked fine and the package was published correctly, which was what I intended to do immediately after merging the last PR anyway, so no harm done!)
The better approach seems to be to use the `release` event instead and move the tag-check condition into the job definition. This is also nice because we can add additional publish jobs to the same workflow as necessary. 
I tested this locally with [act](https://github.com/nektos/act) to verify that the job runs or does not runs as expected based on the tag present …
=> Publish on release events

.github/workflows/publish-packages.yml, packages/design-system/package.json
We need to run `yarn build` when deploying the `design-system` package. Currently the deployed package just has a `package.json` and a `README.md` in it.
Going to follow-up by immediately publishing.
N/A
=> Make sure that we run yarn build when publishing

packages/design-system/package.json, packages/design-system/src/components/ErrorPage/ErrorPage.stories.tsx, packages/design-system/src/components/ErrorPage/ErrorPage.styles.tsx, packages/design-system/src/components/ErrorPage/ErrorPage.tsx, packages/design-system/src/index.tsx
Adds an `ErrorPage` wrapper that can be used across apps to unify our error pages. In storybook, there are two examples that will be pulled into Case Triage immediately.
Closes #12 
=> Add error page

packages/design-system/package.json, packages/design-system/src/components/Dropdown/Dropdown.stories.tsx, packages/design-system/src/components/Dropdown/Dropdown.styles.tsx, packages/design-system/src/components/Dropdown/Dropdown.tsx, packages/design-system/src/components/Dropdown/DropdownContext.ts, packages/design-system/src/components/Dropdown/DropdownFocusManager.ts, packages/design-system/src/components/Dropdown/DropdownMenu.tsx, packages/design-system/src/components/Dropdown/DropdownMenuItem.tsx, packages/design-system/src/components/Dropdown/DropdownToggle.tsx, packages/design-system/src/components/Dropdown/index.ts, packages/design-system/src/components/Icon/IconSVG.tsx, packages/design-system/src/index.tsx
This implements an accessible dropdown menu for use in the Case Triage tool.
* `DropdownFocusManager` is a class that takes the `<Dropdown/>` element ref, and is able to move focus throughout the component.
* Element has support for up/down/tab/enter/escape key presses
https://user-images.githubusercontent.com/437360/116614685-18b38380-a8ef-11eb-8887-b907a57d77c3.mov
> Description here
=> Add `Dropdown` component

packages/design-system/package.json, packages/design-system/src/components/Modal/Modal.stories.tsx, packages/design-system/src/components/Modal/Modal.tsx, packages/design-system/src/styles/index.ts, packages/design-system/yarn.lock
In Spotlight I extended the `Modal` component with some features that I expect would be universally applicable: 
1. A translucent color and blur effect on the overlay when it's open
2. Preventing the page behind the modal from scrolling while it's open
3. Some styles to make the size of the modal more responsive to small screens and scroll overflowing content
This brings all three of those features into the Design System, and bumps the package version accordingly.
(The scroll locking behavior, unfortunately, does not work in Storybook because it doesn't seem to work in an `iframe`; however, I verified the behavior by installing the package locally in another application).
n/a
These boxes should be checked by reviewers prior …
=> Add overlay styles and scroll lock to Modal

packages/design-system/package.json, packages/design-system/src/components/Modal/Modal.stories.tsx, packages/design-system/src/components/Modal/Modal.tsx
A flaw in my testing when I implemented this feature obscured what was, in retrospect, a pretty glaring bug that prevented the scroll lock feature from working; we were never actually setting the ref on the component that would enable the locking behavior. (It is conditional behind what I thought was just an annoying type safety check, but was actually introducing this problem 😐)
Anyway this fixes that and you can now see the scroll locking behavior in Storybook. Verified the bundle locally against Spotlight (where previously I had failed to remove the redundant scroll-locking behavior implemented there, which is why I didn't see the bug there).
n/a
=> Fix scroll lock behavior when modal is open

packages/design-system/package.json, packages/design-system/src/components/Button/Button.tsx, packages/design-system/src/components/Button/Button.types.ts
Previously we couldn't add html attributes like `aria-label` to our buttons. 
=> Allow `Button`s to accept generic html attributes

packages/design-system/.storybook/main.js, packages/design-system/package.json, packages/design-system/src/components/ChartWrapper/ChartWrapper.stories.mdx, packages/design-system/src/components/ChartWrapper/ChartWrapper.tsx, packages/design-system/src/index.tsx, packages/design-system/src/styles/index.ts, packages/design-system/yarn.lock
This adds a `ChartWrapper` component that does some baseline formatting for Semiotic charts via CSS. I've souped it up beyond what it's been elsewhere (e.g. Spotlight) with some default colors for common chart types and basic tooltip styling.
In addition I used the documentation for this component as a little "Semiotic starter kit" to help onboard folks to the library and demonstrate what the wrapper component does.
There's more that could be added here in the future (more advanced tooltip features, highlighting behavior, a legend component) but this seemed like a good start for now while I had a little slack time! Interested in feedback on whether this documentation is actually useful or if it's too redundant or missing important things.
n/a
These boxes should be checked by the submitter …
=> Add ChartWrapper & Semiotic docs to design system

packages/design-system/package.json, packages/design-system/src/components/Button/Button.stories.tsx, packages/design-system/src/components/Button/Button.styles.tsx, packages/design-system/src/components/Button/Button.tsx, packages/design-system/src/components/Button/Button.types.ts, packages/design-system/src/components/Dropdown/Dropdown.stories.tsx, packages/design-system/src/components/Dropdown/Dropdown.styles.tsx, packages/design-system/src/components/Dropdown/Dropdown.tsx, packages/design-system/src/components/Dropdown/DropdownToggle.tsx
- `Button` supports a "block" variant via the new `shape` property, and a new "borderless" kind. All kind values are applied to block buttons the same way they are to "pill" buttons (which is what the existing kind is named now)
- `Dropdown.Toggle` uses these properties of `Button` instead of implementing its own button. (There were slight discrepancies between the "secondary" styles; secondary now uses the newer styles seen in Case Triage and Spotlight with a gray border, and all button kinds have some additional hover states and transitions now for consistency)
- `Button` supports an "icon button" variant via the `icon` property, which will cause it to render only the named icon component as its children. This component is integrated with the button so it picks up color changes from the …
=> Integrate Dropdown and Button styles

packages/design-system/package.json, packages/design-system/src/components/Toast/Toast.styles.tsx, packages/design-system/src/components/Toast/Toast.tsx, packages/design-system/src/index.ts, packages/design-system/src/styles/zindex.ts
I'll be adding our first usage of the `<Toast/>` component to case-triage shortly. This exports the components into our package.
=> Include `<Toast/>` in `@recidiviz/design-system`

packages/design-system/package.json, packages/design-system/src/components/Dropdown/Dropdown.stories.tsx, packages/design-system/src/components/Dropdown/Dropdown.styles.tsx, packages/design-system/src/components/Dropdown/DropdownMenuItem.tsx, packages/design-system/src/components/Dropdown/DropdownToggle.tsx
Small changes to the Dropdown component family: 
- optionally render a caret in the toggle button by passing a prop (a common enough feature that we shouldn't have to keep reimplementing it)
- fix incorrect typeface in the menu (was picking up system default from user-agent button styles)
- accept any `ReactNode` as an item label, not just strings
> supports https://github.com/Recidiviz/recidiviz-data/issues/7801
=> [Design system] Dropdown extensions

packages/eslint-config/CHANGELOG.md, packages/eslint-config/index.js, packages/eslint-config/package.json
I just realized, thanks to [this PR](https://github.com/Recidiviz/recidiviz-data/pull/8130#discussion_r665709489), that while we were including the `simple-import-sort` plugin here we were never actually applying its rules! This turns them on. 
I'd consider this a breaking change because it will probably introduce lots of linting errors when you update to this downstream; however, they should all be auto-fixable so it shouldn't be a big deal.
n/a
=> [ESLint] Enforce import sort order

packages/design-system/CHANGELOG.md, packages/design-system/package.json, packages/design-system/src/components/Dropdown/DropdownMenuItem.tsx
In Safari, clicking on a dropdown element can sometimes cause the menu to lose focus and close before the click event can actually be handled. This issue is not evident in Storybook but it did appear in real-world use. 
This solution fixes the issue and, as far as I can tell, causes no regressions in targeted browsers, but it's not terribly satisfying. I have not been able to determine:
- why this only affects Safari
- why it happens in the Case Triage application but not in Storybook
- why this even fixes the problem tbh?
I think there is some deeper underlying flaw in the focus management feature that requires some more investigation; I suspect that its internal state gets somehow out of sync with the DOM when the component re-renders but I haven't been able to pin that down after a few …
=> [Design System] Safari dropdown bug

packages/design-system/CHANGELOG.md, packages/design-system/src/components/Dropdown/Dropdown.styles.tsx, packages/design-system/src/components/Dropdown/DropdownToggle.tsx
IE 11, for whatever reason, does not handle an `auto`margin the same as other browsers, which was breaking the little trick we used to override the centering in a `DropdownToggle` when the caret is displayed. This explicitly overrides the `justify-content` style instead, which has the same end result and works in all browsers. 
https://github.com/Recidiviz/recidiviz-data/issues/8235
=> [Design System] position dropdown caret properly in IE11

packages/design-system/CHANGELOG.md, packages/design-system/package.json, packages/design-system/src/components/Toast/Toast.tsx
Accept all props for ToastProvider and pass them through to the underlying library. Some options (e.g. toast placement) can only be set at the provider level; this enables that while preserving the defaults we set in our wrapper component.
> https://github.com/Recidiviz/recidiviz-data/issues/8500 (blocks https://github.com/Recidiviz/recidiviz-data/pull/8556)
=> [Design System] Accept all library props for ToastProvider

packages/design-system/CHANGELOG.md, packages/design-system/package.json, packages/design-system/src/components/Tabs/Tabs.styles.tsx
`TabPanel` components that are not selected may still take up space even though they don't have contents; this may depend on the container styles or even overrides but it's not an uncommon situation. Most browsers seem to be able to handle this but IE 11 does not: invisible tabs may be rendered on top of the active one and intercept mouse events, preventing interaction with the active tab. 
The most hygienic solution (and the one seen in examples provided by React Tabs documentation) is to simply hide tabpanels that don't have the `selected` class applied to them, so that's what I've done here!
https://github.com/Recidiviz/recidiviz-data/issues/8645
=> [Design System] Hide TabPanels that are not selected

packages/design-system/CHANGELOG.md, packages/design-system/package.json, packages/design-system/src/components/Button/Button.styles.tsx, packages/design-system/src/components/Button/Button.tsx, packages/design-system/src/components/Button/Button.types.ts
Using `React.HTMLAttributes<HTMLButtonElement>` does not include typings for the attributes of an `HTMLButtonElement` as I had previously thought. This patch uses `React.HTMLButtonAttributes` which includes these additional typings:
```typescript
interface ButtonHTMLAttributes<T> extends HTMLAttributes<T> {
autoFocus?: boolean;
disabled?: boolean;
form?: string;
formAction?: string;
formEncType?: string;
formMethod?: string;
formNoValidate?: boolean;
formTarget?: string;
name?: string;
type?: 'submit' | 'reset' | 'button';
value?: string | ReadonlyArray<string> | number;
}
```
=> Update `<Button/>` props structure to allow for `HTMLButtonElement` attributes

packages/design-system/package.json, packages/design-system/rollup.config.js, packages/design-system/yarn.lock
Something I realized in the course of building the TN prototypes was that we were bundling all of our dependencies into the distribution files for this package. I don't think it's necessary to do this, as applications using this library are installing all of those packages anyway. I swapped in a different Rollup plugin that automatically marks all dependencies as external and tested the output in a couple of our applications; everything seemed to still work fine. 
Per the bundle analyzer tool that I have also included in this diff, this reduces the bundle size from ~850K to ~80K.
n/a
=> [design-system] don't bundle dependencies

packages/design-system/README.md, packages/design-system/package.json, packages/design-system/scripts/dev-link.sh, packages/design-system/scripts/dev-unlink.sh, packages/design-system/yarn.lock
The previous changes to bundle contents in #70 did nothing to address the duplicate dependencies we had to work around with our `dev-(un)link` scripts, although I thought it might; turns out these were more related to inherent limitation in the `yarn link` tool, not the redundant dependency code that was in the bundle. 
The existing scripts still work fine but here I am proposing a new workflow based on [Yalc](https://www.npmjs.com/package/yalc), which I just ... think is better? Our problem is one of the things it was explicitly created to resolve, and so it does not evidence the same problem with multiple copies of React that our previous scripts were trying to resolve.
n/a
These boxes should be checked by reviewers prior …
=> [design-system] update watch/link scripts to use yalc

packages/design-system/package.json, packages/design-system/src/components/ChartWrapper/ChartWrapper.stories.mdx, packages/design-system/src/components/ChartWrapper/ChartWrapper.tsx, packages/design-system/src/components/Tooltip/Tooltip.stories.tsx, packages/design-system/src/components/Tooltip/Tooltip.tsx, packages/design-system/src/components/Tooltip/TooltipTrigger.stories.tsx, packages/design-system/src/components/Tooltip/TooltipTrigger.tsx, packages/design-system/src/components/Tooltip/index.tsx, packages/design-system/src/index.ts, packages/design-system/yarn.lock
This adopts the `Tooltip` component from the Case Triage application and splits it into two components: 
- `Tooltip` is the tooltip itself
- `TooltipTrigger` wraps a hoverable target and encapsulates the logic for showing and hiding the tooltip based on hover state
The behavior and appearance is mostly identical to Case Triage with some small exceptions: 
- there were animation styles in the original that didn't actually work; I have reimplemented fade in/out animations with React Spring. (Some other incoming components will probably use this library also so I think it's worth adding the dependency now.)
- If you pass it empty contents, it won't render a tooltip. (Previously it would render an empty one, which was never what we wanted.)
There is a use case for `Tooltip` on its own to be …
=> [design-system] Add a Tooltip component

packages/design-system/src/components/Pill/Pill.stories.tsx, packages/design-system/src/components/Pill/Pill.tsx, packages/design-system/src/components/Pill/index.tsx
This adopts the Pill component found in Case Triage with a few minor adjustments and should hopefully preclude further redundant implementations.
Here are the following props the Pill component accepts (* required):
- **color*** | sets color for `background-color` if `filled` is true, `border-color` if `filled` is false or is not explicitly defined
- **filled** | fills `background-color` when true. True if set explicitly or defined as a prop `<Pill filled={true}>` or `<Pill filled>`, false if set explicitly or undefined as a prop `<Pill filled={false}>` or `<Pill>`
- **textColor** | sets text `color`. If `textColor` is undefined as a prop and `filled` is true, it will default to a light text color. This can be overridden by setting textColor to a color value
> Closes #67
These boxes …
=> Add a Pill component

packages/design-system/src/components/Modal/DrawerModal.stories.tsx, packages/design-system/src/components/Modal/DrawerModal.tsx, packages/design-system/src/components/Modal/index.ts
This adopts the DrawerModal component found in Case Triage with a customizable `width` property that should hopefully preclude further redundant implementations.
- **width** | can be adjusted manually by providing a `number`. If not set explicitly, it will default to a (responsive) width of `555`px.
> Closes #69
=> Add a DrawerModal Component

packages/design-system/CHANGELOG.md, packages/design-system/package.json, packages/design-system/src/components/Icon/Icon.stories.tsx, packages/design-system/src/components/Icon/Icon.tsx
Adds a helper for converting icons to data URIs and bumps `design-system` to `3.2.0`
=> Add `iconToDataURI` helper

packages/design-system/CHANGELOG.md, packages/design-system/package.json, packages/design-system/src/components/ChartWrapper/ChartWrapper.tsx
Adds ability to accept and forward a `ref` within the ChartWrapper component.
> Closes #93
=> [design-system] Add ability to accept and forward ref within ChartWrapper component

packages/design-system/CHANGELOG.md, packages/design-system/package.json, packages/design-system/src/components/ChartWrapper/ChartWrapper.tsx
Resolves the below TypeScript error when adding `children` to ChartWrapper component:
`No overload matches this call. Overload 1 of 2, '(props: Omit<Omit<ChartWrapperProps & RefAttributes<HTMLDivElement>, never> & Partial<Pick<ChartWrapperProps & RefAttributes<...>, never>>, "theme"> & { ...; } & { ...; }): ReactElement<...>', gave the following error. Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & Omit<Omit<ChartWrapperProps & RefAttributes<HTMLDivElement>, never> & Partial<...>, "theme"> & { ...; } & { ...; }'. Overload 2 of 2, '(props: StyledComponentPropsWithAs<ForwardRefExoticComponent<ChartWrapperProps & RefAttributes<HTMLDivElement>>, any, {}, never>): ReactElement<...>', gave the following error. Type '{ children: Element; }' has no …
=> [design-system] Fix TypeScript error within `ChartWrapper` when adding `children`

packages/tsconfig/e2e.json, packages/tsconfig/package.json, packages/tsconfig/yarn.lock
This upgrades the `tsconfig` package to version 2.0.0, which upgrades from Node 12 to Node 16. Once merged, I will publish the new package version.
This has been tested alongside the `pulse-dashboard` Node upgrade.
> Part of [#1924](https://app.zenhub.com/workspaces/polaris-614c9f27fa19b10015ddd495/issues/recidiviz/pulse-dashboard/1924)
=> Upgrade to Node 16

packages/design-system/package.json, packages/design-system/src/components/Dropdown/DropdownMenu.tsx, packages/design-system/src/components/Dropdown/DropdownMenuItem.tsx
Adds logic to prevent closing the `DropdownMenu` when the event target is modal content, otherwise a dropdown inside of modals are broken because the menu is closed before the input has a chance to call its `onChange` handler.
This is admittedly pretty hacky, I'm open to other ideas about how to resolve this issue. I have played around with the z-indexes of the modal/modal content/dropdown, but the click event target remains the modal content.
=> [design-system] Add logic to prevent dropdown from closing when item is selected if indicated

packages/design-system/package.json, packages/design-system/src/components/Tooltip/TooltipTrigger.tsx
If tooltip doesn't have enough space on the right move it to the left relative to pointer. Works only when maxWidth is specified.
=> [design-system] Move tooltip to the left if it lacks space from the right

packages/eslint-config/CHANGELOG.md, packages/eslint-config/index.js, packages/eslint-config/package.json, packages/eslint-config/yarn.lock
Breaking upgrade of the eslint-config package to 3.0, which adds support for ESLint 8 and react-scripts 5. Developed in parallel with tooling upgrade in `recidiviz-dashboards` ([PR](https://github.com/Recidiviz/recidiviz-dashboards/pull/2852))
n/a
=> support CRA5 in eslint-config

packages/auth/.eslintrc.js, packages/auth/README.md, packages/auth/license-header.js, packages/auth/src/Auth.test.tsx, packages/auth/src/AuthStore.ts, packages/auth/src/AuthWall.tsx, packages/auth/src/index.ts
I think this makes the component interface more flexible (e.g. consumers may wish to provide their own props to the components that may be rendered) and the type definitions a bit cleaner. I have a reference implementation that uses this interface in [this PR](https://github.com/Recidiviz/recidiviz-data/pull/17974). That would be the first live use case for this library! We will have to publish it after this is merged (it hasn't been published yet so I didn't see any reason to bump the version)
n/a
=> Require nodes as AuthWall props instead of component functions

packages/auth/package.json, packages/auth/src/AuthStore.ts
I belatedly realized that this package wasn't specifying its actual runtime dependencies, which caused an issue downstream when I tried to treat them as transitive when I no longer needed them directly. 
Also to support this I re-exported the `Auth0Settings` type so that I didn't have to have auth0 as a direct dependency downstream just to get the type definition
n/a
=> [auth] declare runtime dependencies

.github/workflows/auto-merge-dependabot.yml
> If Dependabot opens a PR that is a dependency upgrade that is `minor` or `patch`,  we can have Helperbot approve and merge the change. 
> https://github.com/Recidiviz/zenhub-tasks/issues/1513
=> [Security] Auto-merge PRs opened by Dependabot

packages/auth/README.md, packages/auth/package.json, packages/auth/src/Auth.test.tsx, packages/auth/src/AuthStore.ts
To support a pre-login landing page in the JII app we need to be able to check authentication status without immediately redirecting logged-out users to the login flow, and then redirect them later in response to user input. This refactors the existing functionality to allow that, while preserving the behavior of `AuthStore.authenticate()` for backwards compatibility.
https://github.com/Recidiviz/recidiviz-dashboards/issues/5410
=> [Auth] Separate auth check from login redirect

packages/design-system/CHANGELOG.md, packages/design-system/package.json, packages/design-system/src/components/Modal/Modal.tsx
This PR changes the Modal component to forwards the `contentRef` prop to the internal react-modal component.
=> [Design System] Enable contentRef prop in Modal

packages/design-system/CHANGELOG.md, packages/design-system/package.json, packages/design-system/src/components/Modal/Modal.tsx
(PR authored by @matankb, I just had to make another PR to get the actions to run.)
This PR changes the Modal component to forwards the `contentRef` prop to the internal react-modal component.
=> [Design System] Enable contentRef prop in Modal (#182)

packages/design-system/CHANGELOG.md, packages/design-system/package.json, packages/design-system/src/components/Modal/Modal.stories.tsx, packages/design-system/src/components/Modal/Modal.tsx
Add a `disableBackgroundScroll` prop to the Modal component in the design system, which is `true` by default but prevents background scroll from being locked when it is `false`.
This will enable us to implement new designs in Workflows for the opportunity side panel. This side panel uses the DrawerModal component, which inherits from Modal. We would now like the user to be able to interact with the rest of the page while the modal is open; see https://github.com/Recidiviz/recidiviz-dashboards/pull/7280
Is it better to bump the version number in this PR or a separate one?
https://github.com/Recidiviz/recidiviz-dashboards/issues/7185
=> [Design System] Allow Modal component to enable background scrolling

packages/design-system/src/components/Dropdown/Dropdown.stories.tsx, packages/design-system/src/components/Dropdown/Dropdown.styles.tsx
Sets `display: none` when `DropdownMenu` is closed, so that we don't trigger menu item tooltips when menu is closed.
In IA, we wanted to add some tooltips to a menu button's dropdown items and noticed that the hover state was being triggered even when the menu was closed. See that conversation [here](https://github.com/Recidiviz/recidiviz-dashboards/pull/8805#pullrequestreview-2951726926). I am not sure of the history of the Dropdown components but I think `display: none` when closed should be ok. Confirmed the behavior is fixed via stories.
<Details><Summary>Screen recordings for a visual:</Summary>
Before:
https://github.com/user-attachments/assets/a3abdb22-a338-40b1-8324-f52d91fdf136
After:
https://github.com/user-attachments/assets/77a2c5b7-6bd6-4cde-badb-41e3c2edeb4d
</Details> …
=> [Design System] Handle menu items with tooltips
