packages/design-system/package.json
packages/design-system/src/components/Button/Button.styles.tsx

This attribute was missing, and I want to use `link`-style `Button`s in the Case Triage frontend.
N/A

Add missing font-family attribute

---

packages/design-system/package.json
packages/design-system/src/components/Icon/IconSVG.tsx

Adds a new icon we need for Case Triage. https://github.com/Recidiviz/recidiviz-data/pull/7064 shows it in action.
N/A

Add CloseOutlined Icon

---

packages/design-system/src/components/Header/Header.styles.tsx
packages/design-system/src/components/Header/Header.tsx
packages/design-system/src/components/Search/Search.styles.tsx

We want to make the search bar in the header a little more responsive. Here's the approach:
https://user-images.githubusercontent.com/993682/116157760-87a89680-a6bb-11eb-98c5-8091c9fcd29e.mov
N/A

Implement styles to resize search bar

---

packages/design-system/.eslintrc.js
packages/design-system/src/components/ErrorPage/ErrorPage.stories.tsx

[design-system] Forbids import of styled-component/macro. Our rollup bundle will not build when the babel macro is included

---

packages/design-system/src/components/Button/Button.tsx

[design-system] Allow users to attach refs to <Button/>

---

packages/design-system/CHANGELOG.md
packages/design-system/package.json

[design-system] v2.0.0

---

packages/design-system/package.json
packages/design-system/src/components/Icon/IconSVG.tsx

Added three new icons. The immediate need for these is in the new case triage "notes" feature.
> part of https://github.com/Recidiviz/recidiviz-data/issues/7635

[Design System] New icons

---

packages/design-system/CHANGELOG.md

Add `v2.1.0` changelog

---

packages/design-system/CHANGELOG.md

perhaps someday I will remember to do this when I'm supposed to
n/a

changelog for 2.3.0

---

packages/design-system/CHANGELOG.md
packages/design-system/package.json
packages/design-system/src/components/Icon/IconSVG.tsx

Adds a Download icon and bumps the version.
> Closes

[Design System] Add Download icon

---

packages/design-system/CHANGELOG.md
packages/design-system/package.json

Update package version and changelog for release
n/a

[design-system] 2.7.0 version bump

---

packages/design-system/.storybook/preview.js
packages/design-system/CHANGELOG.md
packages/design-system/package.json
packages/design-system/src/components/Button/Button.styles.tsx
packages/design-system/src/components/Dropdown/Dropdown.styles.tsx
packages/design-system/src/components/GlobalStyle/GlobalStyle.ts
packages/design-system/src/components/Search/Search.styles.tsx
packages/design-system/src/components/Toast/Toast.styles.tsx
packages/design-system/src/components/Typography/Headings.tsx
packages/design-system/src/styles/fonts.ts
packages/design-system/src/types/styled-components.d.ts
packages/design-system/yarn.lock

[v3] Move font configuration into a theme; Adds Public Sans

---

packages/design-system/CHANGELOG.md
packages/design-system/package.json
packages/design-system/src/components/Tooltip/Tooltip.stories.tsx
packages/design-system/src/components/Tooltip/Tooltip.tsx
packages/design-system/src/components/Tooltip/TooltipTrigger.stories.tsx
packages/design-system/src/components/Tooltip/TooltipTrigger.tsx

A few small changes to tooltip components, based on some use cases in TN Practices.
closes #87, closes #88, closes #89

Tooltip improvements

---

.github/workflows/nightfall.yml
.nightfalldlp/config.json

> Adding Nightfall DLP scans to Github PRs
> https://app.zenhub.com/workspaces/aurora-5ee070a1d1aec30a3086712b/issues/recidiviz/zenhub-tasks/748

Adding Nightfall DLP scans to Github PRs

---

packages/design-system/CHANGELOG.md
packages/design-system/package.json
packages/design-system/src/components/Loading/Loading.tsx
packages/design-system/src/components/Loading/Loading.types.ts

Give the Loading component props so that the text can be customized for the spinner

Add props for loading spinner text

---

packages/design-system/CHANGELOG.md
packages/design-system/package.json

Increment version for tooltip fixes

Increment version for tooltip fixes

---

.github/workflows/nightfall.yml

> Skip Nightfall checks for Dependabot upgrades

[Security] Skip Nightfall checks for Dependabot upgrades

---

.github/workflows/auto-merge-dependabot.yml

> Renaming token to use Helperbot token
> 

[Security] Renaming token to use Helperbot token

---

.github/workflows/auto-merge-dependabot.yml

> We need to perform a squash and merge approach, rather than a merge commit. This is a requirement in our repo settings.

[Security] Make merge strategy squash and merge

---

packages/design-system/src/components/Tooltip/Tooltip.stories.tsx
packages/design-system/src/components/Tooltip/Tooltip.tsx
packages/design-system/src/components/Tooltip/TooltipTrigger.stories.tsx
packages/design-system/src/components/Tooltip/TooltipTrigger.tsx

Added option to customize tooltip background color for upcoming Overview UI changes

Add customizable background color for tooltip

---

packages/design-system/CHANGELOG.md
packages/design-system/package.json
packages/design-system/src/components/Icon/IconSVG.tsx

Used in new landing page designs
https://github.com/Recidiviz/recidiviz-dashboards/issues/6182

New icons for Opportunities
